DataHive/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('DataHiveApp.urls', 'DataHiveApp'), namespace='DataHiveApp'))
]

DataHiveApp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('dataset/<int:pk>/', views.DataSetDetailView.as_view(), name='dataset.detail'),
    path('dataset/', views.DataSetListView.as_view(), name='dataset.list'),
    path('dataset/rand/', views.random_dataset, name='dataset.rand'),
    path('configurations/', views.config, name='config'),
    path('download/<path:file_url>/', views.download_from_url, name='download'),
    path('', views.index, name='index'),
]

DataHiveApp/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from search_engine.whoosh_functions import search_doc_by_id, get_three_like_this,get_keywords_id

REPOS = (
    ("DATAVERSE", "Harvard Dataverse"),
    ("UCI", "UCI - Machine Learning Repository")
)


# Create your models here.
class DataSet(models.Model):

    title = models.CharField(max_length=250)
    authors = ArrayField(models.CharField(max_length=250), null=True, blank=True)
    abstract = models.TextField(null=True, blank=True)
    no_instances = models.IntegerField(null=True, default=None)
    no_attr = models.IntegerField(null=True, default=None)
    url = models.URLField(unique=True)
    download_url = models.URLField(null=True)
    publication_date = models.DateTimeField(null=True)
    keywords = ArrayField(models.CharField(max_length=300), null=True, blank=True)
    source = models.ForeignKey('RepoMetadata', related_name='datasets', on_delete=models.DO_NOTHING)
    categories = models.ManyToManyField('Category', blank=True)

    def get_files_download_url(self):

        dataverse_file_download_url = "https://dataverse.harvard.edu/api/access/datafiles/{0}"
        uci_file_download_url = ""
        kaggle_file_download_url = ""

        get_url = {
            'DATAVERSE': lambda files: dataverse_file_download_url.format(",".join([f.id_in_source for f in files]))
            ,
            "UCI": (lambda  x: None)
        }

        return get_url[str(self.source)](self.files.all())

    def get_n_files(self):
        return len(self.files.all())

    def get_abstract(self):
        whoosh_data = search_doc_by_id(self.id)
        return whoosh_data['abstract'] if 'abstract' in whoosh_data else None

    def get_description(self):
        whoosh_data = search_doc_by_id(self.id)
        return whoosh_data['description'] if 'description' in whoosh_data else None

    def get_recommended(self):
        recommended = get_three_like_this(self.id)
        return DataSet.objects.filter(pk__in=[r["dataset_id"] for r in recommended]) if recommended else None

    def get_keywords(self):
        return get_keywords_id(self.id)

    def __str__(self):
        return "{0} ({1})".format(self.title, self.source)


class Category(models.Model):
    name = models.CharField(max_length=150, unique=True)

    def __str__(self):
        return self.name


class File(models.Model):
    id_in_source = models.CharField(max_length=250)
    name = models.CharField(max_length=250)
    attributes = ArrayField(models.CharField(max_length=100), null=True, blank=True)
    size = models.CharField(max_length=20, blank=True, null=True)
    file_type = models.CharField(max_length=50, blank=True, null=True)
    dataset = models.ForeignKey('DataSet', related_name='files', on_delete=models.CASCADE)

    def get_file_download_url(self):

        dataverse_file_download_url = "https://dataverse.harvard.edu/api/access/datafiles/{0}"
        uci_file_download_url = "http://archive.ics.uci.edu/ml/"
        kaggle_file_download_url = ""

        get_url = {
            'DATAVERSE': lambda: dataverse_file_download_url.format(self.id_in_source)
            ,
            "UCI": (lambda: self.dataset.download_url+self.id_in_source)
        }

        return get_url[str(self.dataset.source)]()

    def __str__(self):
        return "{0} -- {1}".format(self.name, self.dataset)


class RepoMetadata(models.Model):
    name = models.CharField(max_length=10, choices=REPOS, default='DATAVERSE', unique=True)
    last_fetch_page = models.IntegerField(null=True, blank=True, default=0)
    last_fetch_dataset = models.ForeignKey('DataSet', null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.name


all_models = {
    "DataSet": DataSet,
    "Category": Category,
    "File": File,
    "RepoMetadata": RepoMetadata
}

DataHiveApp/forms.py
from django import forms


class CronConfigForm(forms.Form):
    days = forms.IntegerField(label='Days')
    hours = forms.IntegerField(label='Hours')
    minutes = forms.IntegerField(label='Minutes')

DataHiveApp/views.py
from django.shortcuts import render, redirect
from .forms import CronConfigForm
from .scripts import manage_load_cron
from .models import DataSet
from django.views.generic import DetailView, ListView
from search_engine.whoosh_functions import search_doc
from django.http import StreamingHttpResponse
import requests


def index(request):
    return render(request, 'DataHiveApp/index.html')


def config(request):
    if request.method == 'POST':
        form = CronConfigForm(request.POST)

        if form.is_valid():
            data = form.data
            manage_load_cron.update_cron(**{'minutes': data['minutes'][0],
                                            'hours': data['hours'][0],
                                            'days': data['days'][0]})
            return render(request, 'DataHiveApp/configuration.html', {'form': form})

    else:
        data = manage_load_cron.get_current_cron_config()
        form = CronConfigForm(data) if data != {} else CronConfigForm({'minutes': 1, 'hours': 1, 'days': 1})

    return render(request, 'DataHiveApp/configuration.html', {'form': form})


class DataSetDetailView(DetailView):
    model = DataSet


class DataSetListView(ListView):
    model = DataSet
    paginate_by = 20
    template_name = 'DataHiveApp/dataset_list.html'

    def get_queryset(self):
        queryset = []
        if self.request.GET.get("q"):
            results = search_doc(self.request.GET.get("q"))
            if results:
                queryset = DataSet.objects.filter(pk__in=[result['dataset_id'] for result in results])
        else:
            queryset = DataSet.objects.all().order_by('?')

        return queryset


def download_from_url(request, file_url):
    r = requests.get(file_url, stream=True)
    resp = StreamingHttpResponse(streaming_content=r)
    file_name = file_url.split("/")[-1]
    resp['Content-Disposition'] = 'attachment;filename="'+file_name+'"'
    return resp


def random_dataset(request):
    ds = DataSet.objects.order_by('?').first().id
    return redirect('/dataset/'+str(ds))

DataHiveApp/templates/DataHiveApp/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en-US">
	<head>
		<title>Data Hive</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
        <link rel="shortcut icon" type="image/png" href="{% static 'img/logo.png' %}"/>

		<style>
			hr {
				height: 1px;
				background-color: #cccccc;
				margin-top: 20px;
				margin-bottom: 20px;
				width: 100%;
			}
			.vertical-center {
                margin-top: 5%;
			}
		</style>
	</head>
	<body>
		<nav class="navbar navbar-default">

			<div class="container-fluid">

                {% url 'DataHiveApp:index' as index_url %}
                {% url 'DataHiveApp:config' as config_url %}
                {% url 'DataHiveApp:dataset.list' as dataset_url %}
                {% url 'DataHiveApp:dataset.rand' as dataset_random_url %}


				<div class="navbar-header">

                    <img class="navbar-brand" src="{% static 'img/logo.svg' %}">

					<!--<a class="navbar-brand" href="{{index_url}}">Data Hive</a>-->
				</div>



				<ul class="nav navbar-nav">
					<li {% if request.path == index_url %}class="active"{% endif %}><a href="{{index_url}}">Home</a></li>
                    <li {% if dataset_url in request.path %}class="active"{% endif %}><a href="{{dataset_url}}">Datasets</a></li>
                    <li><a href="{{dataset_random_url}}">Random Dataset</a></li>
				</ul>

   				<ul class="nav navbar-nav navbar-right">
					<li>
                        <form action="{{ dataset_url }}" class="navbar-form" role="search">
                            {% csrf_token %}
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search..." name="q"
                                       value="{{request.GET.q|default_if_none:''}}">
                                <div class="input-group-btn">
                                    <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                                </div>
                            </div>
                        </form>
                    </li>
                    <li {% if request.path == config_url %}class="active"{% endif %}>
                        <a href="{{config_url}}">
                            <i class="fas fa-cog"></i>
                            Configurations
                        </a>
                    </li>
                </ul>
			</div>
		</nav>

		<div class="container">
			{% if title %}
                <h1>{{title}}</h1>
            {% endif %}

			{% block content %}
			{% endblock %}
		</div>

	</body>
</html>

DataHiveApp/templates/DataHiveApp/configuration.html
{% extends 'DataHiveApp/base.html' %}

{% block content %}

	<h1>Configurations</h1>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3> Update cron </h3>
        </div>
        <div class="panel-body">

            <h4>Execute every:</h4>
            <form class="col-md-10 col-md-offset-2"action="{{config_url}}" method="post">
                <div class="form-group">
                    {% csrf_token %}
                    <div class="input-group">
                        {{ form }}
                        <input type="submit" value="Set Cron" />
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

DataHiveApp/templates/DataHiveApp/dataset_detail.html
{% extends 'DataHiveApp/base.html' %}

{% block content %}

{% url 'DataHiveApp:download' as download_url %}

    <div class="panel panel-info">
        <div class="panel-body">
            <div class="col-xs-1">
            <img src="https://www.shareicon.net/download/2016/01/07/699454_education_512x512.png"
                                                        width="25px" style="padding-top:20px"/>
            </div>
            <div class="col-xs-11">
            <h3> {{object.title}} <span class="badge">{{dataset.get_n_files}} files </span> </h3>
            <p>{{dataset.get_abstract | default_if_none:''}}</p>
        </div>
        </div>
    </div>
    <div class="panel panel-info">
        <div class="panel-body">
            <div class="row">
                <div class="col-md-8">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <div class="panel-title pull-left">
                                  <h4>Dataset info</h4>
                            </div>
                            <div class="panel-title pull-right">
                                <small>{{dataset.publication_date | date:"SHORT_DATE_FORMAT"}}</small>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                    <div class="panel panel-info">
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-md-12 ">
                                    <div class="row">
                                        <div class="col-md-12 ">
                                            <h4>Description</h4>
                                        </div>
                                        <div class="col-md-11 col-md-offset-1">
                                            <p>{{dataset.get_description | default_if_none:''}}</p>
                                        </div>
                                        <div class="col-md-12"><hr></div>

                                        <div class="col-md-12 ">
                                            <h4>Authors</h4>
                                        </div>
                                        <div class="col-md-11 col-md-offset-1">
                                            <ul class="list-group">
                                            {% for author in object.authors %}
                                                <li class="list-group-item">{{ author }}</li>
                                            {% empty %}
                                                No authors
                                            {% endfor %}
                                            </ul>
                                        </div>
                                        <div class="col-md-12"><hr></div>

                                        <div class="col-md-12 ">
                                            <h4>Keywords</h4>
                                        </div>
                                        <div class="col-md-11 col-md-offset-1">
                                            <p>
                                                {% if dataset.keywords %}
                                                    {{dataset.keywords | join:" , "  }}
                                                {% else %}
                                                    {{dataset.get_keywords | join:", "}}
                                                {% endif %}
                                            </p>
                                        </div>
                                        <div class="col-md-12"><hr></div>

                                        <div class="col-md-12 ">
                                            <h4>Categories</h4>
                                        </div>
                                        <div class="col-md-11 col-md-offset-1">

                                                <ul class="list-group">
                                                    <div class="row">
                                                    {% if dataset.categories.all %}
                                                        {% for category in dataset.categories.all %}
                                                            <div class="col-md-3">
                                                                <div class="list-group-item">{{category}}</div>
                                                            </div>
                                                        {% endfor %}
                                                    {% else %}
                                                        No categories
                                                    {% endif %}
                                                    </div>
                                                </ul>
                                        </div>


                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <div class="panel-title">
                                <h4>Files </h4>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-info">
                        <div class="panel-body">
                            <div class="row">
                                {% if object.get_files_download_url %}
                                <div class="col-md-12">
                                    <a class="btn btn-info btn-block" href="{{object.get_files_download_url}}">
                                        <i class="glyphicon glyphicon-download-alt"></i>
                                        Download all
                                    </a>
                                    <br>
                                </div>
                                {% endif %}
                                {% for file in object.files.all %}
                                    <div class="col-md-12">
                                        <div class="panel panel-info">
                                            <div class="panel-body">
                                                <div class="row">
                                                    <div class="col-md-9">
                                                        <h4 style="white-space: nowrap; overflow:hidden; text-overflow:ellipsis;">{{file.name}}</h4>
                                                        <p>{{file.size}} - {{file.file_type}}</p>
                                                    </div>
                                                    <div class="col-md-3 vertical-center">
                                                        <a class="btn btn-info"
                                                           href="
                                                           {% if file.dataset.source.name == 'UCI' %}
                                                            {% url 'DataHiveApp:download' file_url=file.get_file_download_url %}
                                                           {% else %}
                                                            {{file.get_file_download_url}}
                                                           {% endif %}
                                                           "
                                                           download>
                                                            <i class="glyphicon glyphicon-download-alt"></i>
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>

                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <div class="panel-title">
                                <h4>Similar datasets</h4>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-info">
                        <div class="panel-body">
                            <div class="row">
                                {% if object.get_recommended %}
                                    {% for ds in object.get_recommended %}
                                        <div class="col-md-12">
                                            <div class="panel panel-info">
                                                <div class="panel-body">
                                                    <div class="row">
                                                        <div class="col-sm-1">
                                                            <img src="https://www.shareicon.net/download/2016/01/07/699454_education_512x512.png"
                                                            width="25px"/>
                                                         </div>
                                                        <div class="col-sm-9">

                                                            <a href="{% url "DataHiveApp:dataset.detail" pk=ds.id %}" ><h4 style=" overflow:hidden; text-overflow:ellipsis;">{{ds.title}} <span class="badge">{{ds.get_n_files}} files </span></h4>
                                                            </a>

                                                            <p>{{ds.get_abstract | default_if_none:"<i>No abstract</i>"}}</p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}
                                {% else %}
                                <div class="col-md-12">
                                    No similar datasets found
                                </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

{% endblock %}

DataHiveApp/templates/DataHiveApp/dataset_list.html
{% extends 'DataHiveApp/base.html' %}

{% block content %}
    {% load extra_filters %}
    <div class="row">
        <div class="col-md-6">
            <h3>Dataset list</h3>
        </div>
        <div class="col-md-6">
            <div class="pull-right vertical-center">
                {{page_obj.paginator.count}} results
            </div>
        </div>
        <div class="col-md-12">
            <hr/>
        </div>
    </div>
    <div class="col-md-10 col-md-push-1">
	{% for dataset in object_list %}
        <div class="panel panel-info">
            <div class="panel-body">
                <div class="col-xs-1">
                <img src="https://www.shareicon.net/download/2016/01/07/699454_education_512x512.png"
                                                            width="25px" style="padding-top:20px"/>
                </div>
                <div class="col-xs-11">
                <h3> <a href="{{dataset.id}}">{{dataset.title}}</a> <span class="badge">{{dataset.get_n_files}} files </span></h3>
                <p>{{dataset.get_abstract | default_if_none:''}}</p>
            </div>
            </div>
        </div>


    {% empty %}
        No datasets found
    {% endfor %}
    </div>

    <div class="clearfix"></div>
    <div class="text-center">
        <ul class="pagination">
        {% if is_paginated %}
            {% if page_obj.number == 1 %}
                <li class="disabled"><span>⇤</span></li>
            {% else %}
                <li><a href={{ request.get_full_path|link_name:1 }}>⇤</a></li>
            {% endif %}
            {% if page_obj.has_previous %}
                <li><a href={{ request.get_full_path|link_name:page_obj.previous_page_number }}>&laquo;</a></li>
            {% else %}
                <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in paginator|proper_paginate:page_obj.number %}
                {% if page_obj.number == i %}
                    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                    <li><a href={{ request.get_full_path|link_name:i }}>{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li><a href={{ request.get_full_path|link_name:page_obj.next_page_number }}>&raquo;</a></li>
            {% else %}
                <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
            {% if page_obj.number == paginator.num_pages %}
                <li class="disabled"><span>⇥</span></li>
            {% else %}
                <li><a href={{ request.get_full_path|link_name:paginator.num_pages }}>⇥</a></li>
            {% endif %}
        {% else %}
            <li class="disabled"><span>&laquo;</span></li>
            <li class="active"><a>1</a></li>
            <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
        </ul>
    </div>


{% endblock %}

DataHiveApp/templates/DataHiveApp/index.html
{% extends 'DataHiveApp/base.html' %}

{% block content %}
{% load static %}
	  <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <div class="row">
            <div class="col-md-2">
            <img width="100%" src="{% static 'img/logo.svg' %}" />
        </div>
        <div class="col-md-10">
            <h1>DataHive</h1>
            <p>Your meta-repository for Machine Learning</p>
        </div>
    </div>


      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Multiple sources</h2>
          <p> At DataHive we curate and sort datasets from multiple sources like Harvard's Dataverse, UCI Machine
          Learning Repository and others so that you can find them all in one place without effort.  </p>
          <p><a class="btn btn-default" href="dataset" role="button">Try it &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Useful insights</h2>
          <p>We have developed a complex recommendation system based on the similarities found between
            the datasets. Thanks to this, you can always find useful transversal data for your research.</p>
          <p><a class="btn btn-default" href="dataset" role="button">Try it &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Always up to date</h2>
          <p>Our database is constantly being updated. Our ecosystem grows day after day. Thanks to
        our community (<i>the hive</i>), we work more efficiently, faster, and to a greater scope. Taste the honey, honey.</p>
          <p><a class="btn btn-default" href="dataset" role="button">Try it &raquo;</a></p>
        </div>
      </div>

      <hr>

      <footer>
        <p>&copy; 2018 DataHive, Inc.</p>
      </footer>
    </div> <!-- /container -->
{% endblock %}